"""add_expires_at_to_token_revocations

Revision ID: ebbb4cc07fe0
Revises: 5973b361f1d4
Create Date: 2026-10-07 16:01:08.030480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbb4cc07fe0'
down_revision = '5973b361f1d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_revocations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.create_index(batch_op.f('ix_token_revocations_expires_at'), ['expires_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_revocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_revocations_expires_at'))
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
